name: Docker CD
on:
  push:
    tags: [ "v*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set variables
        id: vars
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/cubxity/borg:${{ steps.vars.outputs.version }},ghcr.io/cubxity/borg:latest
          secrets: |
            "gpr_username=${{ secrets.GPR_USERNAME }}"
            "gpr_token=${{ secrets.GPR_TOKEN }}"
